### ISSUE TITLE
"local/" in "/site/local/?r=" is missing in links of sparql query results for resource outside the namespace

### ISSUE THREAD

**Issue by cfrancois7** [AKSW/aksw.org#62]
Dear all,

I use the aksw.org template to test the ontowiki platform with our rdf data. When I use the back to site with an instance outside the namespace my sparql query works fine but the links of the sparql result items are `http://localhost/site/r/prefix%my_URI instead` of `http://localhost/site/local/r/prefix%my_URI`. The local/is missing. It's true with the use of helper `{{query ...}}` and with a type page where I use a sparql query.

Do you know where I can fix the code? I've searched in template `Query.phtml` and `Querylist.phtml` but I don't understand yet how the item address of sparql query results are generated.

It seems to be very closed problem with the issue [# 36 of site.ontowiki](https://github.com/AKSW/site.ontowiki/issues/36)

Note: I previously posted this message on the ontowiki and site.ontowiki github but the problem is much more closed with the aksw.org templates.

**Comment by white-gecko** [comment]
The correct place for this issue is the site.extension repository. I think you've filed it already over there: https://github.com/AKSW/site.ontowiki/issues/52
